# test_sentiment.py

# ----------------------------------------------------------------------------#
# NOTE: this is a test file stub, generated by ChatGPT. The stub functions in
# your file may not be easy or even possible to test. Instead, use this file
# to test smaller functions and helper functions where you can.
# ----------------------------------------------------------------------------#

import json
import os

from app import sentiment


def dummy_prof_data():
    # Load the dummy data from the JSON file
    json_path = os.path.join(os.path.dirname(__file__), 'dummy_prof_data.json')
    with open(json_path, 'r') as f:
        return json.load(f)


def test_analyze():
    professor_json = dummy_prof_data()
    result = sentiment.analyze(professor_json)

    assert isinstance(result, dict)
    assert "sentiment" in result["reviews"][0]  # TODO update this
    # TODO more assertions that actually match the transformation
