# test_frontend.py

# ----------------------------------------------------------------------------#
# NOTE: this is a test file stub, generated by ChatGPT. The stub functions in
# your file may not be easy or even possible to test. Instead, use this file
# to test smaller functions and helper functions where you can.
# ----------------------------------------------------------------------------#

import json
import os

from .. import frontend
from .. import sentiment


def dummy_prof_data():
    # Load the dummy data from the JSON file
    json_path = os.path.join(os.path.dirname(__file__), 'dummy_prof_data.json')
    with open(json_path, 'r') as f:
        return json.load(f)


def test_format():
    professor_json = sentiment.analyze(dummy_prof_data())
    formatted = frontend.format(professor_json)

    assert isinstance(formatted, dict)
    # TODO add more assertions that make sense
