name: Lint

on:
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14' # or your desired version
        
      - name: Check Node.js version
        run: node -v  # This will print the Node.js version in the workflow logs

      - name: Install JS dependencies
        run: npm install # or `yarn install` if using Yarn

      - name: Run ESLint
        run: npm run lint # ensure you have a lint script in your package.json

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8' # or your desired version

      - name: Install Python dependencies
        run: pip install -r requirements.txt

      - name: Run Flake8
        run: flake8 . # ensure you have Flake8 installed
